### ISSUE TITLE
NoneType error for some pandora models

### ISSUE THREAD

**Issue by cbaakman** [X-lab-3D/PANDORA#175]
I've run about a thousand pandora models. Most of these succeed, but a substantial number of them don't.

I'm using the following script:

```
#!/usr/bin/env python3

import logging
import sys
import os
from argparse import ArgumentParser

from PANDORA.PMHC import PMHC
from PANDORA.Pandora import Pandora
from PANDORA.Database import Database
import PANDORA


arg_parser = ArgumentParser(description="build a model with PANDORA")
arg_parser.add_argument("allele1", help="name of first MHC allele")
arg_parser.add_argument("allele2", help="name of second MHC allele")
arg_parser.add_argument("epitope", help="sequence of epitope peptide")


if __name__ == "__main__":

    args = arg_parser.parse_args()

    model_id = f"{args.allele1}-{args.allele2}-{args.epitope}".replace('*', '-').replace(':', '-')

    logging.basicConfig(filename=f"/home/baakmanc/pandora-build/{model_id}.log", level=logging.INFO)
    _log = logging.getLogger(__name__)

    ## A. load the pregenerated Database  of all pMHC PDBs as templates
    db = Database.load('/home/baakmanc/PANDORA_database/data/csv_pkl_files/database_c.pkl')
    db.repath("/home/baakmanc/PANDORA_database/data/PDBs", False)

    mhc_class = None
    if args.allele1 == "B2M" or args.allele2 == "B2M":
        mhc_class = "I"

    elif args.allele1.startswith("HLA-") and args.allele2.startswith("HLA-"):
        mhc_class = "II"
    else:
        raise ValueError(f"Cannot determine MHC class from alleles {args.allele1} and {args.allele2}")

    _log.info(f"using mhc class {mhc_class} for {args.allele1} {args.allele2} {args.epitope}")

    ## B. Create Target object
    target = PMHC.Target(id=model_id, MHC_class=mhc_class,
                         allele_type = [args.allele1, args.allele2],
                         peptide=args.epitope,
                         anchors=[],
                         use_netmhcpan = True)

    ## C. Perform modelling
    case = Pandora.Pandora(target, db, output_dir='/projects/0/einf2380/data/vdjdb-pandora-models')

    try:
        case.model()
    except:
        _log.exception(f"running model for {args.allele1} {args.allele2} {args.epitope}")
        raise

```

And I get the following log output:
```
INFO:__main__:using mhc class I for HLA-B*27:05:31 B2M KRWIILGLNK
ERROR:__main__:running model for HLA-B*27:05:31 B2M KRWIILGLNK
Traceback (most recent call last):
  File "/home/baakmanc/PANDORA/PANDORA/Pandora/Pandora.py", line 342, in model
    self.find_template(best_n_templates=best_n_templates, benchmark=benchmark, verbose=verbose)
  File "/home/baakmanc/PANDORA/PANDORA/Pandora/Pandora.py", line 41, in find_template
    print('\tTarget Anchors: %s,%s\n' % (self.target.anchors[0],self.target.anchors[1]))
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home4/baakmanc/pandora_build.py", line 57, in <module>
    case.model()
  File "/home/baakmanc/PANDORA/PANDORA/Pandora/Pandora.py", line 345, in model
    raise Exception('Could not find a template')
Exception: Could not find a template
```

In the attachment is a list of all input combinations that result in this error.
[failed models](https://github.com/X-lab-3D/PANDORA/files/9488392/absent.txt)

**Comment by cbaakman** [comment]
Update: the error only seems to be displayed for MHCI models. The MHCII models from the list just don't output anything. So no model and no error.

**Comment by DarioMarzella** [comment]
Hi Coos, I am not sure but it might depend on the B2M you added to the allele list. We never specify the B2M as it's a constant and it's not even modelled.
Also, are you using the Master branch?
In that branch you have to provide the M and N chain sequence. The development branch tries to retrieve those sequences from the reference sequece database using the allele name, so maybe it's the best option for you at the moment.

**Comment by cbaakman** [comment]
I'll retrieve the sequences of the alleles and try again..
