### ISSUE TITLE
PANDORA does not stop when no anchors are found

### ISSUE THREAD

**Issue by LarsM14** [X-lab-3D/PANDORA#230]
In the case below, the given MHC sequence is not available in NetMHCpan-4.1. Therefor, using netMHCpan = True will not provide predicted anchors. After an error message is given the code keeps running untill it eventually breaks when PANDORA could not find a template. This makes it not clear at a first glance that the anchors are the problem for the failing model.

Output:

        No MHC alpha chain allele was provided. Trying to retrieve it from reference sequences...
        WARNING: no anchor positions provided. Pandora will predict them using NetMHCpan
        ERROR: The provided Target allele is not available in NetMHCpan-4.1
        Predicted anchors: None

        Modelling AAAAAASSSAA...

                Target ID: AAAAAASSSAA
                Target MHC Class: I
                Target Allele:  ['Rano-A1*b']
                Target Peptide: AAAAAASSSAA
        Could not find a template
        Traceback (most recent call last):
         File "/srv/home1/larsm/PANDORA/PANDORA/Pandora/Pandora.py", line 323, in model
          self.find_template(best_n_templates=best_n_templates, benchmark=benchmark, verbose=verbose)
         File "/srv/home1/larsm/PANDORA/PANDORA/Pandora/Pandora.py", line 51, in find_template
          print('\tTarget Anchors: %s\n' % (',').join([str(x) for x in self.target.anchors]))
         TypeError: 'NoneType' object is not iterable

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
         File "/srv/home1/larsm/PANDORA/make_pMHCmodel.py", line 20, in <module>
          case.model()
         File "/srv/home1/larsm/PANDORA/PANDORA/Pandora/Pandora.py", line 326, in model
          raise Exception('Could not find a template')
        Exception: Could not find a template

**Comment by DarioMarzella** [comment]
Thanks a lot for reporting this @LarsM14 . Will add an exception for the next release and close this issue when it's implemented.

**Comment by DarioMarzella** [comment]
Fixed in #314
